### PR TITLE
Adding RSS Feed icon

### PR DESCRIPTION
**Pull request by ghost**
Adding a RSS Feed icon.

Live on http://codepodu.com

screen shot 2013-08-05 at 9 56 02 am

### CODE REVIEW

**Comment by mnapoli** [comment]
:+1:

**Comment by alexgaribay** [comment]
If you move it to the social navigation side, I'll accept it. It seems out of place to me if it's on the actual site navigation portion when it doesn't have any navigational function.

**Comment by ghost** [comment]
@alexgaribay I think the current location suits it. 

I see the social navigation as ways to contact me, and to see more of my work at places other than the current site.

I see the site navigation as references to content on the current site, like pages, and the home page, which is the list of most recent posts. If you think about it, the RSS feed is also a navigation, and is exactly the home page, except in a different format.

Hence, I would consider the site navigation section more apt for the RSS icon, than the social navigation.

**Comment by adamwalz** [comment]
Like all the icons on the social navigation side, this would take you away from the site, not to a new page. In some cases it would open your rss reader or at least pop up an option to do so. I agree with @alexgaribay that it should go on the social navigation side.

**Comment by librehat** [comment]
Agree with @alexgaribay and I've written a patch for adding RSS icon into social navigation bar.
Live on my [blog](http://en.librehat.com). Below is the patch content.

```
diff --git a/source/_includes/navigation.html b/source/_includes/navigation.html
index 48f9058..dcd3299 100644
--- a/source/_includes/navigation.html
+++ b/source/_includes/navigation.html
@@ -21,6 +21,9 @@
     {% if site.flickr_user %}
     <li><a href="http://flickr.com/photos/{{ site.flickr_user }}" title="Flickr Profile"><i class="icon-flickr social-navbar"></i></a></li>
     {% endif %}
+    {% if site.subscribe_rss %}
+    <li><a href="{{ site.subscribe_rss }}" title="RSS Feed"><i class="icon-rss-sign social-navbar"></i></a></li>
+    {% endif %}

     {% if site.email %}
     <li><a href="mailto:{{ site.email }}" title="Email"><i class="icon-envelope social-navbar"></i></a></li>
```

**Comment by ghost** [comment]
Alright, I acquiesce. I'll change the PR in a bit :)

**Comment by ghost** [comment]
@alexgaribay PR changed :)

**Pull request closed without merging**
